apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: child-workflow
  namespace: argo
spec:
  templates:
    - name: main
      container:
        name: ""
        image: docker/whalesay:latest
        command:
          - cowsay
        args:
          - Hello from Child Workflow!
  entrypoint: main
