apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operate-workflow-binding
  namespace: argo-events
subjects:
  - kind: ServiceAccount
    name: operate-workflow-sa
    namespace: argo-events
roleRef:
  kind: Role
  name: operate-workflow-role
  apiGroup: rbac.authorization.k8s.io
