apiVersion: v1
kind: Pod
metadata:
  annotations:
    branch: CRS-54980-NSS-SPIKE-Supply-Timeout-Issue
    project: SIP.StoreManagementSyncAPI
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  creationTimestamp: "2024-11-06T16:34:16Z"
  generateName: crs-54980-nss-spike-cb-storemanagementsyncapi-v1-66c9575bc7-
  labels:
    app: crs-54980-nss-spike-cb-storemanagementsyncapi
    config: dev
    env: dev
    managed-by: service-workflow-library
    pod-template-hash: 66c9575bc7
    version: v1
  name: crs-54980-nss-spike-cb-storemanagementsyncapi-v1-66c9575bcrltk8
  namespace: store
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: crs-54980-nss-spike-cb-storemanagementsyncapi-v1-66c9575bc7
    uid: a994f6be-01ef-4085-8d74-8259a68270a2
  resourceVersion: "1231778482"
  uid: aeb5432e-dc6a-40c9-a31e-5e9167d0259d
spec:
  containers:
  - env:
    - name: BRANCH_NAME
      value: CRS-54980-NSS-SPIKE-Supply-Timeout-Issue
    - name: DEPLOY_NAME
      value: crs-54980-nss-spike-cb-storemanagementsyncapi
    - name: DEPLOY_ENV
      value: dev
    - name: ASPNETCORE_ENVIRONMENT
      value: Testing
    - name: OTEL_SERVICE_NAME
      value: storemanagementsyncapi-dev
    - name: AppName
      value: storemanagementsyncapi
    - name: ApexDBSettings__ConnectionString
      valueFrom:
        secretKeyRef:
          key: DEV_ApexDBSettings__ConnectionString
          name: apexdbstring
    - name: DatabaseSettings__BasketDBConnectionString
      valueFrom:
        secretKeyRef:
          key: DEV_DatabaseSettings__BasketDBConnectionString
          name: basketdbstring
    - name: ConfigbrokerDBSettings__ConnectionString
      valueFrom:
        secretKeyRef:
          key: DEV_ConfigbrokerDBSettings__ConnectionString
          name: configbrokerdbstring
    - name: ASPNETCORE_URLS
      value: http://*:8080
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-collector-service.monitoring.svc.cluster.local:4317
    - name: OTEL_METRICS_EXPORTER
      value: prometheus
    - name: OTEL_PROPAGATORS
      value: tracecontext,baggage,b3,b3multi
    image: sipapexdev.azurecr.io/storemanagementsyncapi:CRS-54980-NSS-SPIKE-Supply-Timeout-Issue.8a91b434
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sleep
          - "20"
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /api/v1.0/checkhealth
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    name: storemanagementsyncapi
    ports:
    - containerPort: 8080
      name: http-standard
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /api/v1.0/readytoaccepttraffic
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-qsgfs
      readOnly: true
  dnsConfig:
    options:
    - name: ndots
      value: "2"
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-twmapps1305-19150385-vmss00003h
  nodeSelector:
    app: sipapi
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 1000
    seLinuxOptions:
      level: s0:c123,c456
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: app
    operator: Equal
    value: twmapp
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kube-api-access-qsgfs
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-11-06T16:34:24Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-11-06T16:34:16Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-11-06T16:34:46Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-11-06T16:34:46Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-11-06T16:34:16Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://3a052ad0f8f266498e2fd91039b1251e23e949485210c2b897c0013f80420d3a
    image: sipapexdev.azurecr.io/storemanagementsyncapi:CRS-54980-NSS-SPIKE-Supply-Timeout-Issue.8a91b434
    imageID: sipapexdev.azurecr.io/storemanagementsyncapi@sha256:f2a71313f7ac5c2d3cd0cfe683d42ef1153fd4e4118926aeef82c203f097420c
    lastState: {}
    name: storemanagementsyncapi
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-11-06T16:34:23Z"
  hostIP: 10.152.33.139
  hostIPs:
  - ip: 10.152.33.139
  phase: Running
  podIP: 10.152.34.47
  podIPs:
  - ip: 10.152.34.47
  qosClass: Burstable
  startTime: "2024-11-06T16:34:16Z"