kind: Secret
apiVersion: v1
metadata:
  name: argo-workflows-webhook-clients
  namespace: argo
# The data keys must be the name of a service account.
stringData:
  # https://developer.github.com/webhooks/securing/
  github.com: |
    type: github
    secret: "GitHubWebhookSecret"
